### ISSUE TITLE
Go back to previous page after edit/update terms

### ISSUE THREAD

**Issue by 99MengXin** [jzohrab/lute#12]
**Is your feature request related to a problem? Please describe.**

Go back to previous page after edit/update terms.

**Describe the solution you'd like**

eg. You have 20 pages of terms, you go to page 11, edit and save one of those terms, and it should stay on page 11.

**Describe alternatives you've considered**

Use `command`+click to pop up a new window on macOS.

**Additional context**

I use phpMyAdmin instead for the moment.

**Comment by jzohrab** [comment]
Fixed in `develop` branch.  e.g:

![image](https://user-images.githubusercontent.com/1637133/226130413-a29404a5-a377-4f1b-8d1e-b3a02b7ada29.png)

click on "forward", edit and save, and Lute goes back to same page:

![image](https://user-images.githubusercontent.com/1637133/226130463-eb173883-c801-4d54-863a-8f23ecf84750.png)

**Comment by jzohrab** [comment]
This is in v1.1.7.

**Comment by jzohrab** [comment]
Verified in my install.  @99MengXin , please re-open if you install it and it doesn't work for you.  Cheers and thanks for the idea! z
