### ISSUE TITLE
Ability to remove "Mark rest as known" button

### ISSUE THREAD

**Issue by asakura42** [jzohrab/lute#57]
This button is so confusing and easy to press by occasion. How can I remove it?

**Comment by jzohrab** [comment]
Double checking: you mean this one?

<img width="276" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/915d7d81-bfc3-4bd4-8900-75f1d1ad46bf">

Ah, drag that you find it confusing. :-)  I don't often use that one, I usually use the one in the middle.

You can hide it by using a custom style (ref the wiki https://github.com/jzohrab/lute/wiki/Customizing-Styles)  Add the following to your `data/custom_styles/custom_styles.css` file:

```
#footerMarkRestAsKnown { display: none; }
```

and the page will look like this:

<img width="235" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/fecf417c-d697-4a0d-accd-17f500ba1b74">

The only slight hassle is that the "mark all as known" button won't be shown on the final page of any book:

<img width="264" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/50419008-82c5-4777-8537-56ca20f06e6b">

But maybe that's ok.  Does that work for you?

**Comment by jzohrab** [comment]
I might get rid of that leftmost checkmark, I do t think it adds much value.

**Comment by asakura42** [comment]
Thank you, @jzohrab, I'll check it when I come home. Anyway these two checkmarks may create a mess in a terms list If anybody press them occasionally. Maybe create some popup window that will ask user if he/she really wants to tag all words as known?

Anyway for me personally this will be good: 
```
#footerMarkRestAsKnown { display: none; }
#footerMarkRestAsKnownNextPage { display: none; }
```

Thank you for such a good and easy-to-install LWT fork. That's beautiful.

**Comment by jzohrab** [comment]
>Anyway for me personally this will be good

Super.

> Maybe create some popup window that will ask user if he/she really wants to tag all words as known?

It's a good idea, with some drawbacks (see below), so I'm not going to do this for now.  Thank you for the suggestion though! :-)

Confirming "set all to well-known"

I use Lute a /lot/ and so adding a confirmation would be annoying for me.  Maybe I could add a custom popup, but that starts to add a lot of code (a surprising amount, ballpark 8 hours, partly because I'm not sure how to do some of it).  And I could also add a .env file configuration, but that requires more docs and explanation.

Initial rough estimate:

* add "prompt mark as well-known" user setting to settings table: 0.25 h
* render user setting to page javascript so that "confirm" box is shown or not: 0.5 h   (prob high, but who knows?)
* custom javascript popup/overlay with "don't show this message again" checkbox: 3 h (I don't know how to do this :-) so need to investigate)
* change the checkmarks to call the popup or just post: 0.5 h
* save state on post if checkmark set: 0.5 h
* user acceptance tests: 2 h  (not sure how to access the modal pop-up)
* tutorial tweak and wiki documentation: 0.5 h
